# YAML file for Tangram GenePattern module
# TODO: to set up Dockerfile dependencies using
name: essencdna
channels:
  - conda-forge
dependencies:
  - python=3.12.2
  - pip
  - pip:
      - matplotlib==3.9.0
      - numpy==1.26.4
      - pandas==2.2.0
      - scipy==1.13.1
      - seaborn==0.13.2